// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzfbhrzhhntwnuopjcxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZmJocnpoaG50d251b3BqY3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTc5NDQsImV4cCI6MjA3NDEzMzk0NH0.V71dEkKOyUocqCAmfoTaVPLFNhM-AB87WMNXoidRZP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});